language: node_js
node_js:
  - "10"

branches:
  only:
    - master
    - prod

addons:
  chrome: stable

before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli@latest

install: npm install

script:
  - ng lint
  - ng test --code-coverage

before_deploy:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then ng build --aot --prod --base-href https://aloha-349e8.firebaseapp.com/; fi
  - if [ "$TRAVIS_BRANCH" == "prod" ]; then ng build --aot --prod --base-href https://aloha-prod-2309.firebaseapp.com/; fi

deploy:
  - provider: firebase
    skip_cleanup: true
    token: $FIREBASE_TOKEN
    project: "aloha-349e8"
    on:
      branch: master

  - provider: firebase
    skip_cleanup: true
    token: $FIREBASE_TOKEN
    project: "aloha-prod-2309"
    on:
      branch: prod
