language: node_js
node_js:
  - "10"

branches:
  only:
    - master

addons:
  chrome: stable

before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli@latest

install: npm install

script:
  - ng lint
  - ng test --code-coverage

before_deploy:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then ng build --aot --prod --base-href https://xtr-2309.firebaseapp.com/; fi

deploy:
  - provider: firebase
    skip_cleanup: true
    token: $FIREBASE_TOKEN
    project: "xtr-2309"
    on:
      branch: master
